In [1]:
import pandas as pd

In [30]:
df1 = pd.read_csv("cleanedData.csv")
df1.head()

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=_uQrJ0TkZlc,Python Full Course for Beginners,python tutorial,22447,46484976,1226186,61315
1,https://www.youtube.com/watch?v=kqtD5dpn9C8,Python for Beginners - Learn Coding with Pytho...,python tutorial,3606,23266146,532774,26625
2,https://www.youtube.com/watch?v=rfscVS0vtbw,Learn Python - Full Course for Beginners [Tuto...,python tutorial,16012,48131277,1109421,45939
3,https://www.youtube.com/watch?v=t8pPdKYpowI,Python Tutorial for Beginners - Learn Python i...,python tutorial,19890,6599656,167519,4008
4,https://www.youtube.com/watch?v=K5KVEU3aaeQ,Python Full Course for Beginners [2025],python tutorial,7341,4613318,112457,3020

In [31]:
df2 = pd.read_csv("top_600_youtube_videos_2023.csv")
df2.head()

,title,duration,view_count,like_count,comment_count,duration_seconds
0,Let's see if you dare next time #Shorts #017,PT18S,246200629,1572774.0,942.0,18.0
1,[6번] 식당 업소용 음식포장 비닐랩 절단기,PT15S,160984366,1472323.0,678.0,15.0
2,Khaby Lame react epic moments #shorts #kabhylame,PT19S,96455747,2312319.0,2203.0,19.0
3,Polina Knoroz's Cute Moment in Sports #shorts,PT35S,91902366,1397067.0,930.0,35.0
4,Salute to indian army🇮🇳❤️💯 #army #trending #vi...,PT30S,85157682,1973374.0,0.0,30.0

In [32]:
df2['url'] = 'No URL'
df2['category'] = 'Unknown'

print(df2.head())

                                               title duration  view_count  \
0       Let's see if you dare next time #Shorts #017    PT18S   246200629
1                           [6번] 식당 업소용 음식포장 비닐랩 절단기    PT15S   160984366
2   Khaby Lame react epic moments #shorts #kabhylame    PT19S    96455747
3      Polina Knoroz's Cute Moment in Sports #shorts    PT35S    91902366
4  Salute to indian army🇮🇳❤️💯 #army #trending #vi...    PT30S    85157682

   like_count  comment_count  duration_seconds     url category
0   1572774.0          942.0              18.0  No URL  Unknown
1   1472323.0          678.0              15.0  No URL  Unknown
2   2312319.0         2203.0              19.0  No URL  Unknown
3   1397067.0          930.0              35.0  No URL  Unknown
4   1973374.0            0.0              30.0  No URL  Unknown

In [33]:

df2 = df2[df1.columns]


print(df2.columns)

Index(['url', 'title', 'category', 'duration_seconds', 'view_count',
       'like_count', 'comment_count'],
      dtype='object')

In [34]:
df = pd.concat([df1, df2], ignore_index=True)

print(df.head(10))

                                           url  \
0  https://www.youtube.com/watch?v=_uQrJ0TkZlc
1  https://www.youtube.com/watch?v=kqtD5dpn9C8
2  https://www.youtube.com/watch?v=rfscVS0vtbw
3  https://www.youtube.com/watch?v=t8pPdKYpowI
4  https://www.youtube.com/watch?v=K5KVEU3aaeQ
5  https://www.youtube.com/watch?v=Z1Yd7upQsXY
6  https://www.youtube.com/watch?v=b093aqAZiPU
7  https://www.youtube.com/watch?v=qwAFL1597eM
8  https://www.youtube.com/watch?v=nluUYtejoIE
9  https://www.youtube.com/watch?v=fWjsdhR3z3c

                                               title         category  \
0                   Python Full Course for Beginners  python tutorial
1  Python for Beginners - Learn Coding with Pytho...  python tutorial
2  Learn Python - Full Course for Beginners [Tuto...  python tutorial
3  Python Tutorial for Beginners - Learn Python i...  python tutorial
4            Python Full Course for Beginners [2025]  python tutorial
5  Python Tutorial for Absolute Beginners #1 - Wh...  python tutorial
6                  👩‍💻 Python for Beginners Tutorial  python tutorial
7  Python Tutorial for Beginners (with mini-proje...  python tutorial
8  Python Basics: Your FIRST Program in Under a M...  python tutorial
9  Learn Python in Less than 10 Minutes for Begin...  python tutorial

   duration_seconds  view_count  like_count  comment_count
0           22447.0    46484976   1226186.0        61315.0
1            3606.0    23266146    532774.0        26625.0
2           16012.0    48131277   1109421.0        45939.0
3           19890.0     6599656    167519.0         4008.0
4            7341.0     4613318    112457.0         3020.0
5            1478.0     9375185    203512.0         8571.0
6            3801.0     4159842     90575.0         3079.0
7           31314.0      993222     20712.0          615.0
8              25.0      745778     10707.0           96.0
9             630.0     1142001     26536.0          670.0

In [35]:

df = df.sort_values(by='url', ascending=False)
df = df.drop_duplicates(subset='title', keep='first').reset_index(drop=True)

In [36]:
df

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=zuiU_mD-p0c,This ONE Bible Verse Boosted My Faith #Shorts,religious content,55.0,1097261,165069.0,45568.0
1,https://www.youtube.com/watch?v=ztFAl1To3Wo,Ever tried Crispy Banana Bonda 🤤#shorts,food recipes,52.0,95273478,1468403.0,6862.0
2,https://www.youtube.com/watch?v=zpQ_jC57W4E,Camera Flash tip for beginners - Godox v1 lamp...,photography tutorials,23.0,479077,9712.0,92.0
3,https://www.youtube.com/watch?v=zlomFl0KSVQ,Extend Background Photo - Short Photoshop Tuto...,photography tutorials,31.0,198509,7118.0,24.0
4,https://www.youtube.com/watch?v=zeKkx4NsvCg,Og And Saaho Idharu Brothers Ani Telusundhi | ...,cinema content,24.0,27017,940.0,2.0
...,...,...,...,...,...,...,...
2194,No URL,FULL MATCH — CM Punk v. Randy Orton: WrestleMa...,Unknown,1160.0,847563,25470.0,1028.0
2195,No URL,Kayal - Promo | 18 Mar 2023 | Sun TV Serial | ...,Unknown,32.0,823549,11012.0,86.0
2196,No URL,"The $15,000,000 Audi Hoonitron is the CRAZIEST...",Unknown,60.0,833084,92265.0,851.0
2197,No URL,NY Woman Delivers An AMAZING Speech,Unknown,60.0,961371,82375.0,5708.0
2198,No URL,✅ MISA DE HOY lunes 11 de Diciembre 2023 - Pad...,Unknown,3710.0,113137,23035.0,761.0

In [37]:
df['title'].duplicated().sum()

np.int64(0)

In [38]:
df.isna().sum()

url                  0
title                0
category             0
duration_seconds     4
view_count           0
like_count           3
comment_count       11
dtype: int64

In [39]:
df['duration_seconds'] = df['duration_seconds'].fillna(df['duration_seconds'].median())
df['comment_count'] = df['comment_count'].fillna(df['comment_count'].median())
df['like_count'] = df['like_count'].fillna(df['like_count'].median())

In [40]:
df.isna().sum()

url                 0
title               0
category            0
duration_seconds    0
view_count          0
like_count          0
comment_count       0
dtype: int64

In [41]:
df.info

<bound method DataFrame.info of                                               url  \
0     https://www.youtube.com/watch?v=zuiU_mD-p0c
1     https://www.youtube.com/watch?v=ztFAl1To3Wo
2     https://www.youtube.com/watch?v=zpQ_jC57W4E
3     https://www.youtube.com/watch?v=zlomFl0KSVQ
4     https://www.youtube.com/watch?v=zeKkx4NsvCg
...                                           ...
2194                                       No URL
2195                                       No URL
2196                                       No URL
2197                                       No URL
2198                                       No URL

                                                  title  \
0         This ONE Bible Verse Boosted My Faith #Shorts
1               Ever tried Crispy Banana Bonda 🤤#shorts
2     Camera Flash tip for beginners - Godox v1 lamp...
3     Extend Background Photo - Short Photoshop Tuto...
4     Og And Saaho Idharu Brothers Ani Telusundhi | ...
...                                                 ...
2194  FULL MATCH — CM Punk v. Randy Orton: WrestleMa...
2195  Kayal - Promo | 18 Mar 2023 | Sun TV Serial | ...
2196  The $15,000,000 Audi Hoonitron is the CRAZIEST...
2197                NY Woman Delivers An AMAZING Speech
2198  ✅ MISA DE HOY lunes 11 de Diciembre 2023 - Pad...

                   category  duration_seconds  view_count  like_count  \
0         religious content              55.0     1097261    165069.0
1              food recipes              52.0    95273478   1468403.0
2     photography tutorials              23.0      479077      9712.0
3     photography tutorials              31.0      198509      7118.0
4            cinema content              24.0       27017       940.0
...                     ...               ...         ...         ...
2194                Unknown            1160.0      847563     25470.0
2195                Unknown              32.0      823549     11012.0
2196                Unknown              60.0      833084     92265.0
2197                Unknown              60.0      961371     82375.0
2198                Unknown            3710.0      113137     23035.0

      comment_count
0           45568.0
1            6862.0
2              92.0
3              24.0
4               2.0
...             ...
2194         1028.0
2195           86.0
2196          851.0
2197         5708.0
2198          761.0

[2199 rows x 7 columns]>

In [42]:
df.head(5)

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=zuiU_mD-p0c,This ONE Bible Verse Boosted My Faith #Shorts,religious content,55.0,1097261,165069.0,45568.0
1,https://www.youtube.com/watch?v=ztFAl1To3Wo,Ever tried Crispy Banana Bonda 🤤#shorts,food recipes,52.0,95273478,1468403.0,6862.0
2,https://www.youtube.com/watch?v=zpQ_jC57W4E,Camera Flash tip for beginners - Godox v1 lamp...,photography tutorials,23.0,479077,9712.0,92.0
3,https://www.youtube.com/watch?v=zlomFl0KSVQ,Extend Background Photo - Short Photoshop Tuto...,photography tutorials,31.0,198509,7118.0,24.0
4,https://www.youtube.com/watch?v=zeKkx4NsvCg,Og And Saaho Idharu Brothers Ani Telusundhi | ...,cinema content,24.0,27017,940.0,2.0

In [43]:
# Save to CSV
df.to_csv('integrateddd_data.csv', index=False)


print("Integrated dataset saved to 'integrateddd_data.csv'")

Integrated dataset saved to 'integrateddd_data.csv'