In [1]:
import pandas as pd

In [13]:
df1 = pd.read_csv("1000_educational_channels_CLEAN.csv")
df1.head(50)

,Channel_Name,Channel_ID,Channel_URL,Views_Last_Year,Likes_Last_Year,Comments_Last_Year,Videos_Counted
0,ABC Educational Channel,UC4eJ_rAyzxH9XZEj76ZMzww,https://www.youtube.com/channel/UC4eJ_rAyzxH9X...,2157,41,0,12
1,Educational Channel,UCXx6kmgnS9h8SH8vZ_ZJThg,https://www.youtube.com/channel/UCXx6kmgnS9h8S...,1392,27,1,12
2,Meekah - Educational Videos for Kids,UCx3RchaoRFpDpB60x7xRREw,https://www.youtube.com/channel/UCx3RchaoRFpDp...,590233,3599,0,12
3,Kids Tv - Preschool Learning Videos,UCpnDeduW4x-ww_UOaUAH6WQ,https://www.youtube.com/channel/UCpnDeduW4x-ww...,125970,436,0,12
4,Toddler Learning Videos For Kids - Lucas & Fri...,UCYqksDldZTkKmsrBb4OGJ9g,https://www.youtube.com/channel/UCYqksDldZTkKm...,86765949,183510,0,12
5,The Education channel,UCLMIKkA5FJdw-0aFlF0IfWw,https://www.youtube.com/channel/UCLMIKkA5FJdw-...,13565,292,77,12
6,Myanmar Education Channel,UChGaOLaNOD0wsfLTS18_OWg,https://www.youtube.com/channel/UChGaOLaNOD0ws...,1731,42,0,12
7,Kids TV Education,UCED40MHCEessQ7ntAwj0h8w,https://www.youtube.com/channel/UCED40MHCEessQ...,41733,90,0,12
8,The Home Education Channel,UCL2alPuTI3-FgXO7r8-LNGQ,https://www.youtube.com/channel/UCL2alPuTI3-Fg...,1145,14,0,12
9,Kids Learn and Grow - Educational Videos,UCGxE9I3vpwj9973SaW72tqg,https://www.youtube.com/channel/UCGxE9I3vpwj99...,8528144,1240,0,12
10,Guyana Learning Channel,UCiLHDXgCNJM0xXtBCpfhCyg,https://www.youtube.com/channel/UCiLHDXgCNJM0x...,9526,115,8,12
11,Brain Education TV,UCoqtKR3DyzMoSaMxqSyrdig,https://www.youtube.com/channel/UCoqtKR3DyzMoS...,18302,1222,116,12
12,Smart Kids - Educational & Fun TV,UCdNmlmZh1tn2x2-sQBzYKBw,https://www.youtube.com/channel/UCdNmlmZh1tn2x...,5156,13,0,12
13,SUVI Education Channel,UCMKbFe_WqCf7z0HuthmjAag,https://www.youtube.com/channel/UCMKbFe_WqCf7z...,1249,60,8,12
14,Education Channel With Azra,UCa-2Nehwy-B56iHv_LsVDHA,https://www.youtube.com/channel/UCa-2Nehwy-B56...,442,25,0,12
15,Smile and Learn - English,UCxoDMG0tvaYO5Xobvtqw5nw,https://www.youtube.com/channel/UCxoDMG0tvaYO5...,198045,1017,0,12
16,Education channel,UCSR7N8BJiUcoVcv4VsZCkEg,https://www.youtube.com/channel/UCSR7N8BJiUcoV...,2878,83,5,12
17,Happy Learning English,UC8eJxPzmvTb12v7LlZUJcLQ,https://www.youtube.com/channel/UC8eJxPzmvTb12...,4298,34,0,12
18,Mr. English Channel,UCgnORmgQrecRE4gmTolU5Sw,https://www.youtube.com/channel/UCgnORmgQrecRE...,296994,16991,1246,12
19,قناة نور التعليمية- Nour Educational Channel,UCZJobfYxzdVRr4c6ukvp5pA,https://www.youtube.com/channel/UCZJobfYxzdVRr...,2658,25,0,12
20,Orthoxcel Eductional Channel,UCmVbUt7Mu2eA4MOtW0MrklA,https://www.youtube.com/channel/UCmVbUt7Mu2eA4...,2646,86,3,12
21,Blocks Universe,UCpbpfcZfo-hoDAx2m1blFhg,https://www.youtube.com/channel/UCpbpfcZfo-hoD...,295928,1052,0,12
22,Community Education Channel,UCYqm-7xA_iN8IlX4uX3HtNg,https://www.youtube.com/channel/UCYqm-7xA_iN8I...,6036,57,1,12
23,FACT EDUCATION,UCqsEbBpD2u2KXPPEVvoCR3w,https://www.youtube.com/channel/UCqsEbBpD2u2KX...,51684428,960981,9073,12
24,EDUCATION CHANNEL BD,UC2o1elgn18QdeuV81lM2PKw,https://www.youtube.com/channel/UC2o1elgn18Qde...,3879,0,25,12
25,HD Education,UCAZiVpzu6oHHLcBQixHH0yg,https://www.youtube.com/channel/UCAZiVpzu6oHHL...,260703,497,529,12
26,Nile stars educational Channel,UCMbGPYQoF9ky33pH0KpNFGw,https://www.youtube.com/channel/UCMbGPYQoF9ky3...,6481,61,0,12
27,StudyTube Education,UC12JuiJvbK7D00jF8X4qJyw,https://www.youtube.com/channel/UC12JuiJvbK7D0...,54744,4348,584,12
28,A for Education,UCOuEJDjmHLq-_6yJvhrVg3Q,https://www.youtube.com/channel/UCOuEJDjmHLq-_...,5563,172,35,12
29,KIDS EDUCATION TV,UCfXFR2kzkohmuENg5XoJwJg,https://www.youtube.com/channel/UCfXFR2kzkohmu...,9936,176,0,12
30,sr education channel,UC_0Wx1Rmxf5NkcAWXsDw5JA,https://www.youtube.com/channel/UC_0Wx1Rmxf5Nk...,27137,2632,219,12
31,DOWNTOWN Education,UCSLCRl9oriS5EnS4x0jcBHA,https://www.youtube.com/channel/UCSLCRl9oriS5E...,20821,726,143,12
32,ثقافة Education,UCflJHOhhHn4RP1kzoXgK_sg,https://www.youtube.com/channel/UCflJHOhhHn4RP...,84537,476,12,12
33,Free Animated Education,UCbaZa-dV7h9QOLzrzrY363w,https://www.youtube.com/channel/UCbaZa-dV7h9QO...,24090,538,24,12
34,Crimson Education,UC_f7C43GUWhif5_yPsamdfA,https://www.youtube.com/channel/UC_f7C43GUWhif...,22409,336,20,12
35,HZad Education - Coaching Central,UCWpTxzueSK9ThaYPUrtly7Q,https://www.youtube.com/channel/UCWpTxzueSK9Th...,18301,204,7,12
36,Virginia Department of Education,UCrbxl9wHScrWKWIEoUWNIfQ,https://www.youtube.com/channel/UCrbxl9wHScrWK...,8647,0,0,12
37,Nail Career Education,UCTldDNXS4GeChcmwm55mXYQ,https://www.youtube.com/channel/UCTldDNXS4GeCh...,214722,11313,540,12
38,تربية مبسطة Education simplifiée,UCCgdwkx4Gt_kTElSrO-8oKA,https://www.youtube.com/channel/UCCgdwkx4Gt_kT...,40862,1443,339,12
39,Stanford Graduate School of Education,UCYtp74jGqSdHJdIh9v61MNQ,https://www.youtube.com/channel/UCYtp74jGqSdHJ...,2839,55,5,12
40,Harvard Graduate School of Education,UC1Up4TuDvGZraQUj9vxUaxQ,https://www.youtube.com/channel/UC1Up4TuDvGZra...,46589,926,3,12
41,Challenge Education,UCzo0ngMIuyewdCllmuEbgww,https://www.youtube.com/channel/UCzo0ngMIuyewd...,1018,77,2,12
42,Panorama Education,UClpz8CxhcmNG7YnFdl6PiQQ,https://www.youtube.com/channel/UClpz8CxhcmNG7...,3361,19,0,12
43,West Virginia Department of Education,UCF3TJkDHHLWgYXaxAnrIR7w,https://www.youtube.com/channel/UCF3TJkDHHLWgY...,6379,37,0,12
44,"Department of Education, Victoria",UCKhPMMVm-98ZlveM0VbnCGA,https://www.youtube.com/channel/UCKhPMMVm-98Zl...,679956,11,0,12
45,MS Board of Education Live Stream,UCJW2DTReF-JELb_gpeVJhFw,https://www.youtube.com/channel/UCJW2DTReF-JEL...,5066,0,0,12
46,Education 4u,UCKS34cSMNaXaySe2xgXH-3A,https://www.youtube.com/channel/UCKS34cSMNaXay...,3430,45,7,12
47,Arkansas Department of Education,UCO_a5SM0kwrHZPrzXBa_ZKQ,https://www.youtube.com/channel/UCO_a5SM0kwrHZ...,2691,11,0,12
48,Educational Partners International,UCNhZwQoXDq1zoNi-VAagnIQ,https://www.youtube.com/channel/UCNhZwQoXDq1zo...,7046,329,88,12
49,New Jersey Department of Education,UCtgQgwb0px-rUOZPaz-rysQ,https://www.youtube.com/channel/UCtgQgwb0px-rU...,2768,25,0,12

In [10]:
df2 = pd.read_csv("1000_entertainment_channels_CLEAN.csv")
df2

,Channel_Name,Channel_ID,Channel_URL,Views_Last_Year,Likes_Last_Year,Comments_Last_Year,Videos_Counted
0,All Week Entertainment,UCPELdRVBaHlYAKJpjR0hJZQ,https://www.youtube.com/channel/UCPELdRVBaHlYA...,222615,5751,170,12
1,ANS Entertainment,UC8mlgT6I0aSexwFPsOgMG_g,https://www.youtube.com/channel/UC8mlgT6I0aSex...,4219608,172867,8999,12
2,Entertain Train,UCQkuCY-t01khJBsI5x4vF0Q,https://www.youtube.com/channel/UCQkuCY-t01khJ...,187726,2419,81,12
3,REAL TV,UC2LDKJzY2xZu8pynYnY5N4Q,https://www.youtube.com/channel/UC2LDKJzY2xZu8...,1220973,24818,4473,12
4,Channel 4 Entertainment,UCz1hQ68G3XPVYEBoFDgSjcQ,https://www.youtube.com/channel/UCz1hQ68G3XPVY...,512925,6889,493,12
...,...,...,...,...,...,...,...
585,Only Live Music Videos,UCzuskiw671HtmFT0PHDNf2w,https://www.youtube.com/channel/UCzuskiw671Htm...,79,3,0,12
586,Sonic Music Videos,UCHi-GiBFzOrBqToZvtY1FMQ,https://www.youtube.com/channel/UCHi-GiBFzOrBq...,743287,8051,227,12
587,GoAnimate Music Videos,UCSjziqEoS42F_3iHz1H8QmA,https://www.youtube.com/channel/UCSjziqEoS42F_...,307,7,0,12
588,AI metal music videos - Clostomy Destruction,UCIQdCAw_BTDxjCeUuP2Zx6Q,https://www.youtube.com/channel/UCIQdCAw_BTDxj...,238813,10921,566,12
589,Female Muscle Music Videos (A.I.),UCsbYG04QwPW2fyz8TWwzGxQ,https://www.youtube.com/channel/UCsbYG04QwPW2f...,6645,220,11,12

In [4]:
print(df1.columns)
print(df2.columns)

Index(['Channel_Name', 'Channel_ID', 'Channel_URL', 'Views_Last_Year',
       'Likes_Last_Year', 'Comments_Last_Year', 'Videos_Counted'],
      dtype='object')
Index(['Channel_Name', 'Channel_ID', 'Channel_URL', 'Views_Last_Year',
       'Likes_Last_Year', 'Comments_Last_Year', 'Videos_Counted'],
      dtype='object')

In [96]:
df1 = df1.drop_duplicates(subset='Channel_ID')
df2 = df2.drop_duplicates(subset='Channel_ID')

In [97]:
df.duplicated(subset='Channel_ID').sum()

np.int64(0)

In [98]:
# Keep only the first occurrence of each channel nameeee
df = df.drop_duplicates(subset='Channel_Name', keep='first')

In [99]:
df.duplicated(subset='Channel_Name').sum()

np.int64(0)

In [100]:
df = pd.concat([df1, df2], ignore_index=True)

In [101]:
edu_keywords = [
    'education', 'educational', 'learn', 'learning',
    'academy', 'school', 'university', 'college',
    'science', 'math', 'physics', 'chemistry',
    'biology', 'history', 'geography',
    'engineering', 'programming', 'coding',
    'tutorial', 'course'
]

In [102]:
def classify_channel(name):
    name = str(name).lower()
    for keyword in edu_keywords:
        if keyword in name:
            return 'Educational'
    return 'Entertainment'

In [103]:
df['Channel_Type'] = df['Channel_Name'].apply(classify_channel)

In [104]:
print(df['Channel_Type'].value_counts())
df[['Channel_Name', 'Channel_Type']].head(10)

Channel_Type
Entertainment    635
Educational      381
Name: count, dtype: int64

                                        Channel_Name Channel_Type
0                            ABC Educational Channel  Educational
1                               Educational Channel   Educational
2               Meekah - Educational Videos for Kids  Educational
3                Kids Tv - Preschool Learning Videos  Educational
4  Toddler Learning Videos For Kids - Lucas & Fri...  Educational
5                             The Education channel   Educational
6                          Myanmar Education Channel  Educational
7                                  Kids TV Education  Educational
8                         The Home Education Channel  Educational
9           Kids Learn and Grow - Educational Videos  Educational

In [95]:
df

,Channel_Name,Channel_ID,Channel_URL,Views_Last_Year,Likes_Last_Year,Comments_Last_Year,Videos_Counted,Channel_Type
0,ABC Educational Channel,UC4eJ_rAyzxH9XZEj76ZMzww,https://www.youtube.com/channel/UC4eJ_rAyzxH9X...,2157,41,0,12,Educational
1,Educational Channel,UCXx6kmgnS9h8SH8vZ_ZJThg,https://www.youtube.com/channel/UCXx6kmgnS9h8S...,1392,27,1,12,Educational
2,Meekah - Educational Videos for Kids,UCx3RchaoRFpDpB60x7xRREw,https://www.youtube.com/channel/UCx3RchaoRFpDp...,590233,3599,0,12,Educational
3,Kids Tv - Preschool Learning Videos,UCpnDeduW4x-ww_UOaUAH6WQ,https://www.youtube.com/channel/UCpnDeduW4x-ww...,125970,436,0,12,Educational
4,Toddler Learning Videos For Kids - Lucas & Fri...,UCYqksDldZTkKmsrBb4OGJ9g,https://www.youtube.com/channel/UCYqksDldZTkKm...,86765949,183510,0,12,Educational
...,...,...,...,...,...,...,...,...
1011,Only Live Music Videos,UCzuskiw671HtmFT0PHDNf2w,https://www.youtube.com/channel/UCzuskiw671Htm...,79,3,0,12,Entertainment
1012,Sonic Music Videos,UCHi-GiBFzOrBqToZvtY1FMQ,https://www.youtube.com/channel/UCHi-GiBFzOrBq...,743287,8051,227,12,Entertainment
1013,GoAnimate Music Videos,UCSjziqEoS42F_3iHz1H8QmA,https://www.youtube.com/channel/UCSjziqEoS42F_...,307,7,0,12,Entertainment
1014,AI metal music videos - Clostomy Destruction,UCIQdCAw_BTDxjCeUuP2Zx6Q,https://www.youtube.com/channel/UCIQdCAw_BTDxj...,238813,10921,566,12,Entertainment
1015,Female Muscle Music Videos (A.I.),UCsbYG04QwPW2fyz8TWwzGxQ,https://www.youtube.com/channel/UCsbYG04QwPW2f...,6645,220,11,12,Entertainment

In [105]:
print(df.columns)

Index(['Channel_Name', 'Channel_ID', 'Channel_URL', 'Views_Last_Year',
       'Likes_Last_Year', 'Comments_Last_Year', 'Videos_Counted',
       'Channel_Type'],
      dtype='object')