In [1]:
import pandas as pd

In [10]:
df1 = pd.read_csv("1000_entertainment_channels_CLEAN.csv")
df1['Category'] = 'Entertainment'
df1.to_csv("1000_entertainment_channels_CLEAN.csv", index=False)
df1.head(50)

,Channel_Name,Channel_ID,Channel_URL,Views_Last_Year,Likes_Last_Year,Comments_Last_Year,Videos_Counted,Category
0,All Week Entertainment,UCPELdRVBaHlYAKJpjR0hJZQ,https://www.youtube.com/channel/UCPELdRVBaHlYA...,222615,5751,170,12,Entertainment
1,ANS Entertainment,UC8mlgT6I0aSexwFPsOgMG_g,https://www.youtube.com/channel/UC8mlgT6I0aSex...,4219608,172867,8999,12,Entertainment
2,Entertain Train,UCQkuCY-t01khJBsI5x4vF0Q,https://www.youtube.com/channel/UCQkuCY-t01khJ...,187726,2419,81,12,Entertainment
3,REAL TV,UC2LDKJzY2xZu8pynYnY5N4Q,https://www.youtube.com/channel/UC2LDKJzY2xZu8...,1220973,24818,4473,12,Entertainment
4,Channel 4 Entertainment,UCz1hQ68G3XPVYEBoFDgSjcQ,https://www.youtube.com/channel/UCz1hQ68G3XPVY...,512925,6889,493,12,Entertainment
5,Green TV Entertainment,UCF2ltLX1dnPa6-L1paPaMzw,https://www.youtube.com/channel/UCF2ltLX1dnPa6...,16664,408,1,12,Entertainment
6,E! Entertainment,UCj7V_ikJOXO9RC8at6kYfHQ,https://www.youtube.com/channel/UCj7V_ikJOXO9R...,2160288,77134,1152,12,Entertainment
7,Music & Entertainment Channel,UCyVlMYT6Mdd07Z3j72xVFpg,https://www.youtube.com/channel/UCyVlMYT6Mdd07...,14435,665,353,12,Entertainment
8,Real entertainment tv,UCJb5shn4LSDtcZbBlftCzTQ,https://www.youtube.com/channel/UCJb5shn4LSDtc...,44034,722,212,12,Entertainment
9,"Regal Entertainment, Inc.",UC69I8egELqWywoX5wrh2KxQ,https://www.youtube.com/channel/UC69I8egELqWyw...,99400,255,4,12,Entertainment
10,Channel i Entertainment,UCO5DuUbUSJNS6A7tgfOLpaA,https://www.youtube.com/channel/UCO5DuUbUSJNS6...,4618,80,14,12,Entertainment
11,Manipur Entertainment Channel,UClu7ojroyfSWwfkNm0wuXtQ,https://www.youtube.com/channel/UClu7ojroyfSWw...,497921,18382,1002,12,Entertainment
12,Samoa Entertainment Media & Tv Channel,UCduyDTgXGEvyubB4maVbrvw,https://www.youtube.com/channel/UCduyDTgXGEvyu...,49010,0,112,12,Entertainment
13,M Entertainment Channel,UCn3WTm4r1MLCHSkZ_SR_dsA,https://www.youtube.com/channel/UCn3WTm4r1MLCH...,13653,506,11,12,Entertainment
14,Masha Entertainment,UC7Su1hPIl-1RSwI85X8-nEQ,https://www.youtube.com/channel/UC7Su1hPIl-1RS...,84265,729,4,12,Entertainment
15,New Entertainment Channel,UCGB71uL9AVZhFRhLPBBqQIA,https://www.youtube.com/channel/UCGB71uL9AVZhF...,14101,1152,95,12,Entertainment
16,IMedia Entertainment - أي ميديا منوعات,UCK8yLItIh5CQc3A4owYZy2A,https://www.youtube.com/channel/UCK8yLItIh5CQc...,84705,616,15,12,Entertainment
17,Raw Entertainment,UCH8ZPpZObpa4zLKPjK0qDXw,https://www.youtube.com/channel/UCH8ZPpZObpa4z...,1316529,10924,1170,12,Entertainment
18,SET India,UCpEhnqL0y41EpW2TvWAHD7Q,https://www.youtube.com/channel/UCpEhnqL0y41Ep...,68255,680,55,12,Entertainment
19,Channel Entertainment,UCPhDgvuPHvixa1kKo75stpg,https://www.youtube.com/channel/UCPhDgvuPHvixa...,1262798,7850,639,12,Entertainment
20,Entertainment TV,UCGfzK4SUo2ehKYwnOEnQIFQ,https://www.youtube.com/channel/UCGfzK4SUo2ehK...,793,5,9,12,Entertainment
21,Family Entertainment Bd,UC4qEoWs2pzfmqoLbDyqFKew,https://www.youtube.com/channel/UC4qEoWs2pzfmq...,26468542,615051,16245,12,Entertainment
22,ENTERTAINMENT TV,UCYlSOe290OlzYydqGka53BA,https://www.youtube.com/channel/UCYlSOe290OlzY...,23910,289,25,12,Entertainment
23,Edutainment TV,UCEie8R9wzUvZCn2atFJorFg,https://www.youtube.com/channel/UCEie8R9wzUvZC...,3316341,17377,853,12,Entertainment
24,Flix Entertainment,UCQd1-WFKgDrSlmg3pnkzgXA,https://www.youtube.com/channel/UCQd1-WFKgDrSl...,8950,53,0,12,Entertainment
25,HARANKSH T.V ENTERTAINMENT,UCaSziiSR94gyfM6OuWCZl4w,https://www.youtube.com/channel/UCaSziiSR94gyf...,3823,118,102,12,Entertainment
26,Mekky Entertainment,UCGfXDZ8iUHtVW8XQ97PfP0Q,https://www.youtube.com/channel/UCGfXDZ8iUHtVW...,334801,3810,179,12,Entertainment
27,Entertainment channel Telugu full movies,UCEG4DdvONwaBShw2qu-Vkjg,https://www.youtube.com/channel/UCEG4DdvONwaBS...,297,13,5,12,Entertainment
28,dmc,UCEeFa7t5I0fqpcLGF-36TEw,https://www.youtube.com/channel/UCEeFa7t5I0fqp...,3882,67,3,12,Entertainment
29,Mai Kassab Entertainment,UCe6w-6URHLdOl6JbaIP3iVg,https://www.youtube.com/channel/UCe6w-6URHLdOl...,162247,2243,23,12,Entertainment
30,Entertainment News Shows,UCnL6kKNpLmAAEwXPL0HadOw,https://www.youtube.com/channel/UCnL6kKNpLmAAE...,30387,550,43,12,Entertainment
31,Pearl I TV,UCYCFSvDuXsWcYBIz_IvUx9g,https://www.youtube.com/channel/UCYCFSvDuXsWcY...,3284,0,5,12,Entertainment
32,DK Entertainment,UCm6lMkdlcVTV3Fv9ENgWA9Q,https://www.youtube.com/channel/UCm6lMkdlcVTV3...,3951,29,0,12,Entertainment
33,Yar Thet Pan Audiobook Ent,UCh-oq38CHDbpC_zQLOesA-Q,https://www.youtube.com/channel/UCh-oq38CHDbpC...,14577,603,101,12,Entertainment
34,Entertainment Tonight,UCdtXPiqI2cLorKaPrfpKc4g,https://www.youtube.com/channel/UCdtXPiqI2cLor...,494423,14665,1753,12,Entertainment
35,Wansee Entertainment,UCRrZWZ8p_Jvhjc8w2KW3EBg,https://www.youtube.com/channel/UCRrZWZ8p_Jvhj...,1253089,28607,1437,12,Entertainment
36,ArtSpear Entertainment,UCmv8PJ2JcIsHQ-2ivtziszQ,https://www.youtube.com/channel/UCmv8PJ2JcIsHQ...,8906735,437599,5385,12,Entertainment
37,The Rest Is Entertainment,UCYJpsKWYfZU8kOHZf_tUzQw,https://www.youtube.com/channel/UCYJpsKWYfZU8k...,393037,6335,1286,12,Entertainment
38,Nateland Entertainment,UCzAzMoLwjQTuyqu2QFFzvQQ,https://www.youtube.com/channel/UCzAzMoLwjQTuy...,2765345,27206,712,12,Entertainment
39,Hats Off Entertainment,UCCay-jgoQFnEFsJ8GD6fjzQ,https://www.youtube.com/channel/UCCay-jgoQFnEF...,1130381,41940,7574,12,Entertainment
40,Entertainment,UCFBB-BZE_e5sOVqvEm9pfBA,https://www.youtube.com/channel/UCFBB-BZE_e5sO...,5675953,20002,402,12,Entertainment
41,Warner Bros. Entertainment,UCgKkNPU2Ib7_TcyAl8M2S-w,https://www.youtube.com/channel/UCgKkNPU2Ib7_T...,109717,2082,102,12,Entertainment
42,Hurrdat Entertainment,UC6HUVquRPAaeMF-gD5gtxFA,https://www.youtube.com/channel/UC6HUVquRPAaeM...,58266,2316,648,12,Entertainment
43,Force Of Light Entertainment,UCVrD2WcTHwTJo4A2r0mjK1A,https://www.youtube.com/channel/UCVrD2WcTHwTJo...,114057,9386,2421,12,Entertainment
44,Entertainment LIVE,UCn0M8BcDRGW5ya78cOgzOeA,https://www.youtube.com/channel/UCn0M8BcDRGW5y...,21741,725,11,12,Entertainment
45,Gratienza Entertainment,UC8mtRuNhwBT2_S0qC5ECVyA,https://www.youtube.com/channel/UC8mtRuNhwBT2_...,575772,10882,988,12,Entertainment
46,SPX Entertainment,UCssRwa6rXARIVQ6vl96mctQ,https://www.youtube.com/channel/UCssRwa6rXARIV...,158908,1935,46,12,Entertainment
47,Lightweight Entertainment,UCErVd30C61blOX9hUK-Gk1A,https://www.youtube.com/channel/UCErVd30C61blO...,957480,21839,2507,12,Entertainment
48,Swell Entertainment,UC_HF-dqn4lCs4fEA4GB210g,https://www.youtube.com/channel/UC_HF-dqn4lCs4...,605451,34641,2342,12,Entertainment
49,Red Chillies Entertainment,UCjJKg01HAP01xCLVhDmnLhw,https://www.youtube.com/channel/UCjJKg01HAP01x...,735669,30963,1053,12,Entertainment

In [11]:
df2 = pd.read_csv("1000_educational_channels_CLEAN.csv")
df2['Category'] = 'Educational'
df2.to_csv("1000_educational_channels_CLEAN.csv", index=False)
df2.head(50)

,Channel_Name,Channel_ID,Channel_URL,Views_Last_Year,Likes_Last_Year,Comments_Last_Year,Videos_Counted,Category
0,ABC Educational Channel,UC4eJ_rAyzxH9XZEj76ZMzww,https://www.youtube.com/channel/UC4eJ_rAyzxH9X...,2157,41,0,12,Educational
1,Educational Channel,UCXx6kmgnS9h8SH8vZ_ZJThg,https://www.youtube.com/channel/UCXx6kmgnS9h8S...,1392,27,1,12,Educational
2,Meekah - Educational Videos for Kids,UCx3RchaoRFpDpB60x7xRREw,https://www.youtube.com/channel/UCx3RchaoRFpDp...,590233,3599,0,12,Educational
3,Kids Tv - Preschool Learning Videos,UCpnDeduW4x-ww_UOaUAH6WQ,https://www.youtube.com/channel/UCpnDeduW4x-ww...,125970,436,0,12,Educational
4,Toddler Learning Videos For Kids - Lucas & Fri...,UCYqksDldZTkKmsrBb4OGJ9g,https://www.youtube.com/channel/UCYqksDldZTkKm...,86765949,183510,0,12,Educational
5,The Education channel,UCLMIKkA5FJdw-0aFlF0IfWw,https://www.youtube.com/channel/UCLMIKkA5FJdw-...,13565,292,77,12,Educational
6,Myanmar Education Channel,UChGaOLaNOD0wsfLTS18_OWg,https://www.youtube.com/channel/UChGaOLaNOD0ws...,1731,42,0,12,Educational
7,Kids TV Education,UCED40MHCEessQ7ntAwj0h8w,https://www.youtube.com/channel/UCED40MHCEessQ...,41733,90,0,12,Educational
8,The Home Education Channel,UCL2alPuTI3-FgXO7r8-LNGQ,https://www.youtube.com/channel/UCL2alPuTI3-Fg...,1145,14,0,12,Educational
9,Kids Learn and Grow - Educational Videos,UCGxE9I3vpwj9973SaW72tqg,https://www.youtube.com/channel/UCGxE9I3vpwj99...,8528144,1240,0,12,Educational
10,Guyana Learning Channel,UCiLHDXgCNJM0xXtBCpfhCyg,https://www.youtube.com/channel/UCiLHDXgCNJM0x...,9526,115,8,12,Educational
11,Brain Education TV,UCoqtKR3DyzMoSaMxqSyrdig,https://www.youtube.com/channel/UCoqtKR3DyzMoS...,18302,1222,116,12,Educational
12,Smart Kids - Educational & Fun TV,UCdNmlmZh1tn2x2-sQBzYKBw,https://www.youtube.com/channel/UCdNmlmZh1tn2x...,5156,13,0,12,Educational
13,SUVI Education Channel,UCMKbFe_WqCf7z0HuthmjAag,https://www.youtube.com/channel/UCMKbFe_WqCf7z...,1249,60,8,12,Educational
14,Education Channel With Azra,UCa-2Nehwy-B56iHv_LsVDHA,https://www.youtube.com/channel/UCa-2Nehwy-B56...,442,25,0,12,Educational
15,Smile and Learn - English,UCxoDMG0tvaYO5Xobvtqw5nw,https://www.youtube.com/channel/UCxoDMG0tvaYO5...,198045,1017,0,12,Educational
16,Education channel,UCSR7N8BJiUcoVcv4VsZCkEg,https://www.youtube.com/channel/UCSR7N8BJiUcoV...,2878,83,5,12,Educational
17,Happy Learning English,UC8eJxPzmvTb12v7LlZUJcLQ,https://www.youtube.com/channel/UC8eJxPzmvTb12...,4298,34,0,12,Educational
18,Mr. English Channel,UCgnORmgQrecRE4gmTolU5Sw,https://www.youtube.com/channel/UCgnORmgQrecRE...,296994,16991,1246,12,Educational
19,قناة نور التعليمية- Nour Educational Channel,UCZJobfYxzdVRr4c6ukvp5pA,https://www.youtube.com/channel/UCZJobfYxzdVRr...,2658,25,0,12,Educational
20,Orthoxcel Eductional Channel,UCmVbUt7Mu2eA4MOtW0MrklA,https://www.youtube.com/channel/UCmVbUt7Mu2eA4...,2646,86,3,12,Educational
21,Blocks Universe,UCpbpfcZfo-hoDAx2m1blFhg,https://www.youtube.com/channel/UCpbpfcZfo-hoD...,295928,1052,0,12,Educational
22,Community Education Channel,UCYqm-7xA_iN8IlX4uX3HtNg,https://www.youtube.com/channel/UCYqm-7xA_iN8I...,6036,57,1,12,Educational
23,FACT EDUCATION,UCqsEbBpD2u2KXPPEVvoCR3w,https://www.youtube.com/channel/UCqsEbBpD2u2KX...,51684428,960981,9073,12,Educational
24,EDUCATION CHANNEL BD,UC2o1elgn18QdeuV81lM2PKw,https://www.youtube.com/channel/UC2o1elgn18Qde...,3879,0,25,12,Educational
25,HD Education,UCAZiVpzu6oHHLcBQixHH0yg,https://www.youtube.com/channel/UCAZiVpzu6oHHL...,260703,497,529,12,Educational
26,Nile stars educational Channel,UCMbGPYQoF9ky33pH0KpNFGw,https://www.youtube.com/channel/UCMbGPYQoF9ky3...,6481,61,0,12,Educational
27,StudyTube Education,UC12JuiJvbK7D00jF8X4qJyw,https://www.youtube.com/channel/UC12JuiJvbK7D0...,54744,4348,584,12,Educational
28,A for Education,UCOuEJDjmHLq-_6yJvhrVg3Q,https://www.youtube.com/channel/UCOuEJDjmHLq-_...,5563,172,35,12,Educational
29,KIDS EDUCATION TV,UCfXFR2kzkohmuENg5XoJwJg,https://www.youtube.com/channel/UCfXFR2kzkohmu...,9936,176,0,12,Educational
30,sr education channel,UC_0Wx1Rmxf5NkcAWXsDw5JA,https://www.youtube.com/channel/UC_0Wx1Rmxf5Nk...,27137,2632,219,12,Educational
31,DOWNTOWN Education,UCSLCRl9oriS5EnS4x0jcBHA,https://www.youtube.com/channel/UCSLCRl9oriS5E...,20821,726,143,12,Educational
32,ثقافة Education,UCflJHOhhHn4RP1kzoXgK_sg,https://www.youtube.com/channel/UCflJHOhhHn4RP...,84537,476,12,12,Educational
33,Free Animated Education,UCbaZa-dV7h9QOLzrzrY363w,https://www.youtube.com/channel/UCbaZa-dV7h9QO...,24090,538,24,12,Educational
34,Crimson Education,UC_f7C43GUWhif5_yPsamdfA,https://www.youtube.com/channel/UC_f7C43GUWhif...,22409,336,20,12,Educational
35,HZad Education - Coaching Central,UCWpTxzueSK9ThaYPUrtly7Q,https://www.youtube.com/channel/UCWpTxzueSK9Th...,18301,204,7,12,Educational
36,Virginia Department of Education,UCrbxl9wHScrWKWIEoUWNIfQ,https://www.youtube.com/channel/UCrbxl9wHScrWK...,8647,0,0,12,Educational
37,Nail Career Education,UCTldDNXS4GeChcmwm55mXYQ,https://www.youtube.com/channel/UCTldDNXS4GeCh...,214722,11313,540,12,Educational
38,تربية مبسطة Education simplifiée,UCCgdwkx4Gt_kTElSrO-8oKA,https://www.youtube.com/channel/UCCgdwkx4Gt_kT...,40862,1443,339,12,Educational
39,Stanford Graduate School of Education,UCYtp74jGqSdHJdIh9v61MNQ,https://www.youtube.com/channel/UCYtp74jGqSdHJ...,2839,55,5,12,Educational
40,Harvard Graduate School of Education,UC1Up4TuDvGZraQUj9vxUaxQ,https://www.youtube.com/channel/UC1Up4TuDvGZra...,46589,926,3,12,Educational
41,Challenge Education,UCzo0ngMIuyewdCllmuEbgww,https://www.youtube.com/channel/UCzo0ngMIuyewd...,1018,77,2,12,Educational
42,Panorama Education,UClpz8CxhcmNG7YnFdl6PiQQ,https://www.youtube.com/channel/UClpz8CxhcmNG7...,3361,19,0,12,Educational
43,West Virginia Department of Education,UCF3TJkDHHLWgYXaxAnrIR7w,https://www.youtube.com/channel/UCF3TJkDHHLWgY...,6379,37,0,12,Educational
44,"Department of Education, Victoria",UCKhPMMVm-98ZlveM0VbnCGA,https://www.youtube.com/channel/UCKhPMMVm-98Zl...,679956,11,0,12,Educational
45,MS Board of Education Live Stream,UCJW2DTReF-JELb_gpeVJhFw,https://www.youtube.com/channel/UCJW2DTReF-JEL...,5066,0,0,12,Educational
46,Education 4u,UCKS34cSMNaXaySe2xgXH-3A,https://www.youtube.com/channel/UCKS34cSMNaXay...,3430,45,7,12,Educational
47,Arkansas Department of Education,UCO_a5SM0kwrHZPrzXBa_ZKQ,https://www.youtube.com/channel/UCO_a5SM0kwrHZ...,2691,11,0,12,Educational
48,Educational Partners International,UCNhZwQoXDq1zoNi-VAagnIQ,https://www.youtube.com/channel/UCNhZwQoXDq1zo...,7046,329,88,12,Educational
49,New Jersey Department of Education,UCtgQgwb0px-rUOZPaz-rysQ,https://www.youtube.com/channel/UCtgQgwb0px-rU...,2768,25,0,12,Educational

In [12]:
print(df1.columns)
print(df2.columns)

Index(['Channel_Name', 'Channel_ID', 'Channel_URL', 'Views_Last_Year',
       'Likes_Last_Year', 'Comments_Last_Year', 'Videos_Counted', 'Category'],
      dtype='object')
Index(['Channel_Name', 'Channel_ID', 'Channel_URL', 'Views_Last_Year',
       'Likes_Last_Year', 'Comments_Last_Year', 'Videos_Counted', 'Category'],
      dtype='object')

In [14]:
df = pd.concat([df1, df2], ignore_index=True)

In [23]:
print(df['Category'].value_counts())

Category
Entertainment    590
Educational      426
Name: count, dtype: int64

In [24]:
df.to_csv("integrated Q3.csv", index=False)