In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv("Source 1 CLEANED.csv")
df1.head()

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=_uQrJ0TkZlc,Python Full Course for Beginners,python tutorial,22447,46484976,1226186,61315
1,https://www.youtube.com/watch?v=kqtD5dpn9C8,Python for Beginners - Learn Coding with Pytho...,python tutorial,3606,23266146,532774,26625
2,https://www.youtube.com/watch?v=rfscVS0vtbw,Learn Python - Full Course for Beginners [Tuto...,python tutorial,16012,48131277,1109421,45939
3,https://www.youtube.com/watch?v=t8pPdKYpowI,Python Tutorial for Beginners - Learn Python i...,python tutorial,19890,6599656,167519,4008
4,https://www.youtube.com/watch?v=K5KVEU3aaeQ,Python Full Course for Beginners [2025],python tutorial,7341,4613318,112457,3020

In [4]:
df2 = pd.read_csv("Source 2 CLEANED.csv")
df2.head()

,title,view_count,like_count,comment_count,duration_seconds
0,Let's see if you dare next time #Shorts #017,246200629,1572774,942,18
1,[6번] 식당 업소용 음식포장 비닐랩 절단기,160984366,1472323,678,15
2,Khaby Lame react epic moments #shorts #kabhylame,96455747,2312319,2203,19
3,Polina Knoroz's Cute Moment in Sports #shorts,91902366,1397067,930,35
4,Salute to indian army🇮🇳❤️💯 #army #trending #vi...,85157682,1973374,0,30

In [5]:
df2['url'] = 'No URL'
df2['category'] = 'Unknown'

print(df2.head())

                                               title  view_count  like_count  \
0       Let's see if you dare next time #Shorts #017   246200629     1572774
1                           [6번] 식당 업소용 음식포장 비닐랩 절단기   160984366     1472323
2   Khaby Lame react epic moments #shorts #kabhylame    96455747     2312319
3      Polina Knoroz's Cute Moment in Sports #shorts    91902366     1397067
4  Salute to indian army🇮🇳❤️💯 #army #trending #vi...    85157682     1973374

   comment_count  duration_seconds     url category
0            942                18  No URL  Unknown
1            678                15  No URL  Unknown
2           2203                19  No URL  Unknown
3            930                35  No URL  Unknown
4              0                30  No URL  Unknown

In [6]:

df2 = df2[df1.columns]


print(df2.columns)

Index(['url', 'title', 'category', 'duration_seconds', 'view_count',
       'like_count', 'comment_count'],
      dtype='object')

In [7]:
df = pd.concat([df1, df2], ignore_index=True)

print(df['duration_seconds'].max())

57468

In [8]:

df = df.sort_values(by='url', ascending=False)
df = df.drop_duplicates(subset='title', keep='first').reset_index(drop=True)

In [9]:
df.head(10)

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=zuiU_mD-p0c,This ONE Bible Verse Boosted My Faith #Shorts,religious content,55,1097261,165069,45568
1,https://www.youtube.com/watch?v=ztFAl1To3Wo,Ever tried Crispy Banana Bonda 🤤#shorts,food recipes,52,95273478,1468403,6862
2,https://www.youtube.com/watch?v=zpQ_jC57W4E,Camera Flash tip for beginners - Godox v1 lamp...,photography tutorials,23,479077,9712,92
3,https://www.youtube.com/watch?v=zlomFl0KSVQ,Extend Background Photo - Short Photoshop Tuto...,photography tutorials,31,198509,7118,24
4,https://www.youtube.com/watch?v=zeKkx4NsvCg,Og And Saaho Idharu Brothers Ani Telusundhi | ...,cinema content,24,27017,940,2
5,https://www.youtube.com/watch?v=zcTCJCLCKEA,Grand Celebration of the Twins with Special Pe...,vlogs,838,4989,238,17
6,https://www.youtube.com/watch?v=z_DgvMHnfjc,My go to settings for sports photography in ma...,photography tutorials,14,2327745,95924,583
7,https://www.youtube.com/watch?v=zY6MHzF8ZN0,Just winter things 🥹 #relatable #funny #indian...,funny content,10,15208708,373311,495
8,https://www.youtube.com/watch?v=zR_IarVr2AI,Places In Real Life #travel #explore #adventur...,travelling,16,206057629,6853449,8625
9,https://www.youtube.com/watch?v=zKCCTN736Bs,#vlog | Saturday Vachindante Apudapudu Inthe 😡...,vlogs,1753,37413,808,146

In [10]:
df['title'].duplicated().sum()

0

In [11]:
df.isna().sum()

url                 0
title               0
category            0
duration_seconds    0
view_count          0
like_count          0
comment_count       0
dtype: int64

In [ ]:
df['duration_seconds'] = df['duration_seconds'].fillna(df['duration_seconds'].median())
df['comment_count'] = df['comment_count'].fillna(df['comment_count'].median())
df['like_count'] = df['like_count'].fillna(df['like_count'].median())

In [13]:
df.isna().sum()

url                 0
title               0
category            0
duration_seconds    0
view_count          0
like_count          0
comment_count       0
dtype: int64

In [14]:
df.info

<bound method DataFrame.info of                                               url  \
0     https://www.youtube.com/watch?v=zuiU_mD-p0c
1     https://www.youtube.com/watch?v=ztFAl1To3Wo
2     https://www.youtube.com/watch?v=zpQ_jC57W4E
3     https://www.youtube.com/watch?v=zlomFl0KSVQ
4     https://www.youtube.com/watch?v=zeKkx4NsvCg
...                                           ...
2166                                       No URL
2167                                       No URL
2168                                       No URL
2169                                       No URL
2170                                       No URL

                                                  title  \
0         This ONE Bible Verse Boosted My Faith #Shorts
1               Ever tried Crispy Banana Bonda 🤤#shorts
2     Camera Flash tip for beginners - Godox v1 lamp...
3     Extend Background Photo - Short Photoshop Tuto...
4     Og And Saaho Idharu Brothers Ani Telusundhi | ...
...                                                 ...
2166  Anandha Ragam - Ep 184 | 02 April 2023 | Tamil...
2167  Biggest LIME harvest ever! Tree with 1000s of ...
2168   Kodi Gaha Yata | Episode 24 - (2023-05-27) | ITN
2169   Kodi Gaha Yata | Episode 30 - (2023-06-18) | ITN
2170  ✅ MISA DE HOY lunes 11 de Diciembre 2023 - Pad...

                   category  duration_seconds  view_count  like_count  \
0         religious content                55     1097261      165069
1              food recipes                52    95273478     1468403
2     photography tutorials                23      479077        9712
3     photography tutorials                31      198509        7118
4            cinema content                24       27017         940
...                     ...               ...         ...         ...
2166                Unknown              1326      850284        8476
2167                Unknown              1720      860431       14809
2168                Unknown              1143      868328       14267
2169                Unknown              1133      869933       13633
2170                Unknown              3710      113137       23035

      comment_count
0             45568
1              6862
2                92
3                24
4                 2
...             ...
2166             73
2167            636
2168            543
2169            757
2170            761

[2171 rows x 7 columns]>

In [15]:
df.head(5)

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=zuiU_mD-p0c,This ONE Bible Verse Boosted My Faith #Shorts,religious content,55,1097261,165069,45568
1,https://www.youtube.com/watch?v=ztFAl1To3Wo,Ever tried Crispy Banana Bonda 🤤#shorts,food recipes,52,95273478,1468403,6862
2,https://www.youtube.com/watch?v=zpQ_jC57W4E,Camera Flash tip for beginners - Godox v1 lamp...,photography tutorials,23,479077,9712,92
3,https://www.youtube.com/watch?v=zlomFl0KSVQ,Extend Background Photo - Short Photoshop Tuto...,photography tutorials,31,198509,7118,24
4,https://www.youtube.com/watch?v=zeKkx4NsvCg,Og And Saaho Idharu Brothers Ani Telusundhi | ...,cinema content,24,27017,940,2

In [16]:
# Save to CSV
df.to_csv('Integrated Data Part 1.csv', index=False)


print("Integrated dataset saved to 'Integrated Data Part 1.csv'")

Integrated dataset saved to 'Integrated Data Part 1.csv'