In [41]:
import pandas as pd

In [42]:
df1 = pd.read_csv("Tiktok Data Cleaned.xls")
df1.head()

,username,likes,comments,shares,views,duration_seconds,created_at,url,engagement_rate,date
0,661._miaa,183900,329,3361,826700,9,2024-09-16 17:56:17+00:00,https://www.tiktok.com/@661._miaa/video/741530...,0.226914,2024-09-16
1,chasityromann,236600,379,5518,2600000,15,2024-06-03 22:22:38+00:00,https://www.tiktok.com/@chasityromann/video/73...,0.093268,2024-06-03
2,lindceybeautyy,404000,936,9560,3200000,12,2024-08-04 14:26:09+00:00,https://www.tiktok.com/@lindceybeautyy/video/7...,0.129530,2024-08-04
3,iannelsonnnnn,359300,936,11700,3500000,15,2024-05-28 21:38:48+00:00,https://www.tiktok.com/@iannelsonnnnn/video/73...,0.106267,2024-05-28
4,nightmoonxyz,2391,99,118,48600,21,2025-04-23 04:25:50+00:00,https://www.tiktok.com/@nightmoonxyz/video/749...,0.053663,2025-04-23

In [43]:
df2 = pd.read_csv("Tiktok Source 2 Cleaned.xls")
df2.head()

,videoId,videoUrl,text,hashtag,createTime,likes,comments,shares,views,authorUsername,authorName
0,6862153058223197445,https://www.tiktok.com/@/video/686215305822319...,To the 🐝 🐝 🐝 #fyp,fyp,2020-08-18 02:58:41,72392654,2800855,42489319,889198466,bellapoarch,Bella Poarch
1,6911406868699073798,https://www.tiktok.com/@/video/691140686869907...,😳This is one of my best drawings #dlaciebie #t...,fyp,2020-12-28 20:28:43,52117039,758413,1032348,308104412,franekbielak_art,Franek Bielak
2,7298305522623679752,https://www.tiktok.com/@/video/729830552262367...,🤍🤍 #foryou #fyp #teacher #school #suprise #for...,fyp,2023-11-06 11:12:57,51037805,257879,773108,402493327,metrevelisalii,Salome
3,7523242837467598102,https://www.tiktok.com/@/video/752324283746759...,Appreciating those views😮‍💨 #jet2holidays #fyp...,fyp,2025-07-04 15:04:36,42180875,196827,9259038,343454666,bben9450,BradBen
4,7028775404173413678,https://www.tiktok.com/@/video/702877540417341...,bruh this shit has me WHEEZING #fyp,fyp,2021-11-10 03:18:23,40897424,492158,1973949,251230665,adrianchateau,Adrian Chateau Wiles

In [44]:
# Rename df2 columns to match df1
df2.rename(columns={'authorUsername': 'username', 'createTime': 'created_at'}, inplace=True)

In [45]:
# Engagement = (likes + comments + shares) / views
df2['engagement_rate'] = (df2['likes'] + df2['comments'] + df2['shares']) / df2['views']

# Remove rows with zero views to avoid division by zero
df2 = df2[df2['views'] > 0]

In [46]:
cols_needed = ['username', 'created_at', 'likes', 'comments', 'shares', 'views', 'engagement_rate']

df1_clean = df1[cols_needed]  # df1 already has engagement_rate
df2_clean = df2[cols_needed]

In [47]:
df = pd.concat([df1_clean, df2_clean], ignore_index=True)

In [48]:
df.head(5)

,username,created_at,likes,comments,shares,views,engagement_rate
0,661._miaa,2024-09-16 17:56:17+00:00,183900,329,3361,826700,0.226914
1,chasityromann,2024-06-03 22:22:38+00:00,236600,379,5518,2600000,0.093268
2,lindceybeautyy,2024-08-04 14:26:09+00:00,404000,936,9560,3200000,0.129530
3,iannelsonnnnn,2024-05-28 21:38:48+00:00,359300,936,11700,3500000,0.106267
4,nightmoonxyz,2025-04-23 04:25:50+00:00,2391,99,118,48600,0.053663

In [49]:
df = df.dropna(subset=['created_at'])

In [50]:
df['post_date'] = df['created_at'].str.split(' ').str[0]
# just to takee the date only from column created_at

In [51]:
df['posts_per_day'] = df.groupby(['username', 'post_date'])['post_date'].transform('count') # counts how many posts each user made on that date and repeats that number for all rows of that user on that date.

In [52]:
df['views_per_video'] = df['views'] / 1
df['likes_per_video'] = df['likes'] / 1
df['comments_per_video'] = df['comments'] / 1

In [53]:
print(df[['username', 'created_at', 'post_date', 'posts_per_day', 'engagement_rate']].head(5))

         username                 created_at   post_date  posts_per_day  \
0       661._miaa  2024-09-16 17:56:17+00:00  2024-09-16              1
1   chasityromann  2024-06-03 22:22:38+00:00  2024-06-03              1
2  lindceybeautyy  2024-08-04 14:26:09+00:00  2024-08-04              1
3   iannelsonnnnn  2024-05-28 21:38:48+00:00  2024-05-28              1
4    nightmoonxyz  2025-04-23 04:25:50+00:00  2025-04-23              1

   engagement_rate
0         0.226914
1         0.093268
2         0.129530
3         0.106267
4         0.053663

In [54]:
# Check posting frequency distribution
df['posts_per_day'].value_counts()

posts_per_day
1    2381
2     228
3      18
Name: count, dtype: int64

In [55]:
df

,username,created_at,likes,comments,shares,views,engagement_rate,post_date,posts_per_day,views_per_video,likes_per_video,comments_per_video
0,661._miaa,2024-09-16 17:56:17+00:00,183900,329,3361,826700,0.226914,2024-09-16,1,826700.0,183900.0,329.0
1,chasityromann,2024-06-03 22:22:38+00:00,236600,379,5518,2600000,0.093268,2024-06-03,1,2600000.0,236600.0,379.0
2,lindceybeautyy,2024-08-04 14:26:09+00:00,404000,936,9560,3200000,0.129530,2024-08-04,1,3200000.0,404000.0,936.0
3,iannelsonnnnn,2024-05-28 21:38:48+00:00,359300,936,11700,3500000,0.106267,2024-05-28,1,3500000.0,359300.0,936.0
4,nightmoonxyz,2025-04-23 04:25:50+00:00,2391,99,118,48600,0.053663,2025-04-23,1,48600.0,2391.0,99.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2622,juliachaves_ofc,2024-04-28 22:40:27,6662795,35074,110429,49994660,0.136181,2024-04-28,1,49994660.0,6662795.0,35074.0
2623,juliaglowala,2025-01-30 17:58:54,6658552,27726,557786,45059676,0.160766,2025-01-30,1,45059676.0,6658552.0,27726.0
2624,asadkhan_31,2019-11-29 12:43:19,6657884,10891,137463,65777308,0.103474,2019-11-29,1,65777308.0,6657884.0,10891.0
2625,grandpajordan99,2024-12-21 21:05:43,6649163,35678,552265,50545470,0.143180,2024-12-21,1,50545470.0,6649163.0,35678.0
2626,jaqueline.soaress,2023-08-05 14:03:11,6635931,72265,820703,51730871,0.145540,2023-08-05,1,51730871.0,6635931.0,72265.0

In [56]:
avg_engagement = df.groupby('posts_per_day')['engagement_rate'].mean()
print(avg_engagement)
# Groups videos by number of posts per day.

# Computes the average engagement rate for users who post 1, 2, 3… times per day.
# help uss answer the question Does posting frequency affect engagement?

posts_per_day
1    0.127743
2    0.133881
3    0.085162
Name: engagement_rate, dtype: float64

In [57]:
df.to_csv('Final Integrated Tiktok Data.csv', index=False)


print("Final Integrated Tiktok Data.csv")

Final Integrated Tiktok Data.csv